FROM node:16-alpine
WORKDIR /opt/app
COPY package*.json ./
#COPY node_modules ./
#RUN npm ci --silent
#COPY . ./
#ENV NODE_ENV development
#ENV CHOKIDAR_USEPOLLING true
#EXPOSE 3000
ENTRYPOINT [ "npm", "start" ]
