version: "3.8"

networks:
  proxy-net:
    name: web
  jenkins:

services:

  client-local:
    container_name: client-local
    build:
      context: ../../client
      dockerfile: Dockerfile_without-NGINX
    image: normak458/meal-tracker_client_local
    environment:
      - REACT_APP_API_URL=http://localhost
      - REACT_APP_VERSION=${APP_VERSION}
      - REACT_APP_API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.client.rule=Host(`localhost`)&&PathPrefix(`/`)"
     - "traefik.http.routers.client.entrypoints=web"
    ports:
     - "3000:3000"
    networks:
      - proxy-net
    volumes:
      - ../../client:/opt/app

  api:
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: normak458/meal-tracker_api
    entrypoint: [ "npm", "run", "start:dev" ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_VERSION=${API_VERSION}
      - HOST=${API_URL}
      - PORT=${API_PORT}
      - MONGODB_URI=${MONGODB_URI}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)&&PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "8081:8081"
    networks:
      - proxy-net
    volumes:
      - ../../server:/opt/app
