version: "3.3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
     - ./client/.env
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.client.rule=Host(`localhost`)"
     - "traefik.http.routers.client.entrypoints=web"
    ports:
      - "3000:3000"
    networks:
      - web
    # restart: always
    stdin_open: true
    volumes:
      - ./client:/opt/app
      - /opt/app/node_modules
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
     - ./server/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`localhost`)"
      # - "traefik.http.routers.server.rule=Host(`api.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
    ports:
      - "8081:8081"
    networks:
      - web
    # restart: always
    volumes:
      - ./server:/opt/app
      - /opt/app/node_modules
networks:
  web:
