kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-tracker
      task: api
      role: blue
  template:
    metadata:
      labels:
        app: meal-tracker
        task: api
        role: blue
    spec:
      containers:
      - name: api
        image: normak458/meal-tracker_api:v0.0.1
        imagePullPolicy: IfNotPresent #Always #IfNotPresent
        ports:
        - containerPort: 8081
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                key: FRONTEND_HOST
                name: cloud--env
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                key: MONGODB_URI
                name: cloud--env
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                key: NODE_ENV
                name: cloud--env
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: BACKEND_PORT
                name: cloud--env
      restartPolicy: Always
      volumes: null
