kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-tracker
      task: api
      role: green
  template:
    metadata:
      labels:
        app: meal-tracker
        task: api
        role: green
    spec:
      containers:
      - name: api
        image: normak458/meal-tracker_api:v0.0.2
        imagePullPolicy: Always #Always #IfNotPresent
        ports:
        - containerPort: 8081
        env:
          - name: API_VERSION
            valueFrom:
              configMapKeyRef:
                key: API_VERSION
                name: cloud--env
          - name: HOST
            valueFrom:
              configMapKeyRef:
                key: API_URL
                name: cloud--env
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                key: MONGODB_URI
                name: cloud--env
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                key: NODE_ENV
                name: cloud--env
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: BACKEND_PORT
                name: cloud--env
      restartPolicy: Always
      volumes: null
