apiVersion: v1
kind: ServiceAccount
metadata:
  name: meal-tracker-api

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    port: 8081
  selector:
    app: meal-tracker
    task: api
    role: green

---
