version: "3.8"

networks:
  proxy-net:
    name: web

volumes:
  dbdata:

services:

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"

      - "--log.filePath=/logs/a.log"
      - "--log.level=DEBUG"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - proxy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/traefik/logs/:/logs/
      - ./deploy/traefik/acme/:/acme/
      - ./deploy/traefik/rules.yml:/config/rules.yml
    restart: always

  mongo:
    container_name: mongo
    build:
        context: ../database/db
        dockerfile: Dockerfile
    image: normak458/meal-tracker_mongo
    ports:
      - "27017:27017"
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo.rule=Host(`localhost`)"
      - "traefik.http.routers.mongo.entrypoints=web"
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  client:
    container_name: client
    build:
      context: ../mern/client
      dockerfile: Dockerfile
    image: normak458/meal-tracker_client
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.client.rule=Host(`localhost`)"
     - "traefik.http.routers.client.entrypoints=web"
    ports:
      - "80:80"
    networks:
      - proxy-net
    volumes:
      - ../mern/client:/opt/app

  api:
    build:
      context: ../mern/server
      dockerfile: Dockerfile
    image: normak458/meal-tracker_api
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "8081:8081"
    networks:
      - proxy-net
    volumes:
      - ../mern/server:/opt/app
