version: "3.8"

networks:
  proxy-net:
    name: web
  jenkins:

volumes:
  dbdata:

services:

  rerverse-proxy:
    extends: 
      file: ./extentions/infra.yml
      service: reverse-proxy

  mongo:
    extends:
      file: ./extentions/db.yml
      service: mongo
  
  api:
    extends:
      file: ./extentions/local.yml
      service: api

  client:
    extends:
      file: ./extentions/local.yml
      service: client-local