version: "3.8"

networks:
  proxy-net:
    name: web

volumes:
  dbdata:

services:

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      # - "--entryPoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      - "--log.filePath=/logs/a.log"
      - "--log.level=ERROR"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
    ports:
      - '80:80'
      # - '443:443'
      - '8080:8080'
    networks:
      - proxy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  mongo:
    container_name: mongo
    build:
        context: ../db
        dockerfile: dockerfile
    image: normak458/meal-tracker_mongo
    networks:
      - proxy-net
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  client:
    container_name: client
    build:
      context: ../client
      dockerfile: Dockerfile_without-NGINX
    image: normak458/meal-tracker_client_local
    # env_file:
    #  - ../client/.env
    environment:
      - NODE_ENV=development
      # - REACT_APP_API_URL=http://localhost:8081
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      # - HOST=localhost
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.client.rule=Host(`nutri.localhost`)&&PathPrefix(`/`)"
     - "traefik.http.routers.client.entrypoints=web"
    ports:
     - "3000:3000"
    networks:
      - proxy-net
    # stdin_open: true
    volumes:
      - ../client:/opt/app

  api:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: normak458/meal-tracker_api
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=8081
      # - HOST=localhost:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`nutri.localhost`)&&PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "8081:8081"
    networks:
      - proxy-net
    volumes:
      - ../server:/opt/app
