FROM alpine:3.9

RUN apk add su-exec
RUN apk add --no-cache mongodb
RUN mkdir -p /data/db

WORKDIR /scripts

COPY ./scripts/start.sh start.sh
RUN chmod +x start.sh

VOLUME [ "/data/db" ]

EXPOSE 27017

ENTRYPOINT [ "mongod", "--port", "27017", "--dbpath", "/data/db", "--bind_ip_all" ]
